version: '3.9'

services:
  mysql:
    image: mysql:8
    ports:
      - '3306:3306'
#    restart: always
    environment:
      MYSQL_DATABASE: 'bookshop_db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'rootpw'

    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: